name: final_flutter
description: A new Flutter project.

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  provider: ^6.1.2
  flutter_dotenv: ^5.0.2
  supabase_flutter: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/movies.json
    - lib/assets/wp1945909.jpg
